### ISSUE TITLE
certain manga missing

### ISSUE THREAD

**Issue by Adamlord1** [jparkie/Aizoban#19]
Mangas like mushoku tensei are missing. No genre selector though its a good start keep going.

**Comment by jparkie** [comment]
Once a month, I'll recompile the local database to include the new series. The genre selector is limited to certain sources as some sources are difficult to compile. I can't do what MangaRock nor MangaPhoenix does by having their own servers. MangaRock can afford the infrastructure by a premium of $5 while MangaPhoenix has a premium but manually updates the sources such that series are limited.
