### ISSUE TITLE
Page Number in Immersive Mode

### ISSUE THREAD

**Issue by TSedlar** [jparkie/Aizoban#22]
It'd be quite nice to have a progress bar on immersive mode. An app I used to use before it was taken off the Play Store was MangaCloud, it had a [simple way of displaying progress in the bottom left corner.](https://lh6.googleusercontent.com/fN9eZA1Rx8SSwSlNJzErhfgxPmnUulvS5Ww2z89y42jx1BX1xKXsknbE_weTObuRk8dX7ONyB-w=w1896-h802)

**Comment by jparkie** [comment]
I can't access the link. Can you find an image of another example?

**Comment by TSedlar** [comment]
Hopefully imgur works for you.http://i.imgur.com/JtwRZXk.jpg

**Comment by jparkie** [comment]
I'm not too sure what you want from the photo. I don't see anything in the bottom-left corner. Immersive mode is already implemented for devices which support it.

**Comment by TSedlar** [comment]
In the bottom left corner there is a small dash wish progresses along with the page number that you're on. I.E at page 10/20 the bar would be in the center along the bottom of your screen to stay out of the way.

**Comment by jparkie** [comment]
Like how in Adobe Reader it has the following:

![1](https://lh4.ggpht.com/_kBM21A9kyQQOghahzPyMC1fl2f5gELCI-g-iZxdFbWerxlPJyO21HPi-1TaI7usghc=h900-rw)

If this is the feature request, it seems really simple to implement, and I could do it sometime this week..

**Comment by TSedlar** [comment]
Essentially that, yes. But small enough to not be in the way of the image. It'd be really appreciated.

**Comment by jparkie** [comment]
Understood. I'll mark it as an enhancement and assign it to a milestone if you want to track when the feature will be released. A lot of the logic is preexisting as a page progress is already in the toolbar, so all I need to do is set a small transparent rectangle on the bottom left.

**Comment by TSedlar** [comment]
Sounds great!

**Comment by jparkie** [comment]
I finally got some time this Saturday, so I implemented the feature:

![1](https://cloud.githubusercontent.com/assets/9499097/6092703/f6337866-aeb7-11e4-9167-67218ec84ad3.png)

How is it? It's a small translucent rectangle on the bottom-left corner. It's not in the release yet. I'm a bundle this feature with others before a new update.

**Comment by TSedlar** [comment]
Looks beautiful!

**Comment by jparkie** [comment]
Great! I'll have the update on Google Play probably by Friday the latest.
