### ISSUE TITLE
Next/Previous Chapter Buttons

### ISSUE THREAD

**Issue by dulleh** [jparkie/Aizoban#36]
The floating next/previous chapter buttons' functionality should correspond to reading direction. So clicking the left one when reading right-to-left should go to the next chapter and vice versa.

**Comment by jparkie** [comment]
This will be easy to implement. I'll assign myself to it for now.

**Comment by Tabaluga** [comment]
I explained the buttons cause of the icons < and > for previous / next page . For next chapter I think you should use others icons inspired by media players e.g. << and >>. Best regards
