### ISSUE TITLE
Proposal for Version 2.0.+

### ISSUE THREAD

**Issue by jparkie** [jparkie/Aizoban#37]
I am opening this to document possible proposals for Version 2.0.+.

- With the current Model-View-Presenter pattern, I might implement Interactors to handle certain complex events.
- I am considering of implementing Dagger 1 into the project.
- I am considering to write a suite of instrumentation and unit tests.

Any other suggestions? I really want to polish and organize the source, so when I attend university this September, other people can fork the repository and implement features more easily.

**Comment by dulleh** [comment]
I'd say it's more important  to get everything commented out, documented so that the structures already in place are easy to understand/work with.  
A 'How to Contribute' section in the readme would probably be the first thing to do.

**Comment by jparkie** [comment]
I feel it is a priority to refactor a lot of the code to smaller self-explaining methods, so only comments would be used for complicated operations and testing. I agree the documentation would be important.

**Comment by dulleh** [comment]
What do you mean by self-explaining? Self-contained methods?

**Comment by jparkie** [comment]
Methods which perform one task in small lines of code using descriptive names. Thus, by reading the method calls, you understand what is being accomplished without requiring knowledge of too much implementation. Furthermore, preferring methods which makes the state apparent by preferring functions especiallicy monadic ones.

**Comment by jparkie** [comment]
'SQLiteDatabase' accessed from new 'QueryManager' will have ['enableWriteAheadLogging ()'](http://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html#enableWriteAheadLogging()) to allow concurrent writes and reads from multiple threads. Meanwhile, all `DELETE` calls will have a static `ReentrantReadWriteLock` such that `DELETE` calls acquire a write lock while `SELECT` calls acquire a read lock. This will enforce reads to the database to not fetch data which is being deleted, yet allowing parallel reads. The disadvantage is that each call to a `DELETE` method will block subsequent calls to the same method. As a result, `deleteAllChapters()` will not prevent `deleteAllMangas()` from executing.

**Comment by jparkie** [comment]
Testing https://github.com/davemorrissey/subsampling-scale-image-view to replace `GestureImageView`. It is still compatible with Glide, I believe.

**Comment by jparkie** [comment]
Application is suspended on Google Play. I don't have too much motivation to continue it.

**Comment by cwtldzyn** [comment]
Don't worry, you're still up on [F-Droid](https://f-droid.org/repository/browse/?fdid=com.jparkie.aizoban). Google's a jerk and I'm sure many of your users care about the quality of your app more than the slight inconvenience of downloading it from Github or F-Droid.

**Comment by dulleh** [comment]
It was bound to happen at some point, I suppose. Lots of people will still be using it of course, just won't have as many new users coming on board.

**Comment by Chogos** [comment]
I was really surprised when just one day after I've discovered this app my friend couldn't find it on Google Play after I've recommended it to him. 

I think that it would really be a shame if this app ended this way. So, if it's alright with you I would like to continue developing this app in my spare time since I think that with some additional features it would definitely surpass it's competition.

Please let me know if that would be alright with you.
