### ISSUE TITLE
Sideloaded Manga

### ISSUE THREAD

**Issue by Kussie** [jparkie/Aizoban#38]
One idea that i would dearly love to see implemented would be the ability to include Sideloaded manga (Added from SDCard/manually etc).

One possible approach to implement this might be to add a new source, called say "External" or something along those lines.  This source could then look in a directory (Or series  of directories) that could be configured in the settings areas of the app.

The source could then look at the directory structure and construct a list of manga based on that.
For example in rough Ascii art:

```
/sdcard
  - Mangas
    - Some Manga 1
      - Chapter 1
        - 001.jpg
        - 002.jpg
        - ..etc.. 
```

This could then be used in combination with a users PC/Laptop to add mangas that aren't directly supported through sites currently supported by the app.

**Comment by jparkie** [comment]
I feel this feature request is beyond the scope of this application. It would require a custom file chooser. Then, for the ordering of pages and chapters, because they are provided by the users, no standard format could be enforced to order them unless using complex natural ordering methods which are case dependent. The series will not have any information or thumbnail since again the files are user provided without a standard. After, this metadata should not be fetched from other sources since sources should be resilient thus independent from each other.

There are already many other good applications for this feature on the Google Play store. Incorporating them into this application would require drastic changes.

**Comment by Kussie** [comment]
All good points, i guess for me i am looking for an app i can use to replace MangaWatcher since it has been having all sorts of issues lately and hasn't been updated in a while.  For me personally I'd rather have all of my manga in one place rather than having to switch and swap between apps constantly depending on what i feel like right reading. 

You could however overcome some of these problems relatively straight forward in my view.  Since it's user supplied and belongs to a specific "external" source, metadata collection would not be enabled for that source, and because it belongs to a source it is completely separate from others.  The names of manga and chapters could essentially be based on the folder names, so the top level folder would be the Manga name and any folders under that could be Chapter Names.  As for the sorting the way around that would be to just use natural file sorting based on the name.  So if it doesn't appear correctly it should be up to the user to fix it.  You could supply hints/tips in the app guiding the user and giving ideas on what they should be named.  As for the cover you could look for a specific file say cover.jpg in the root of the manga's folder and if it doesn't exists use the first image you find from the first chapter, or even just have a generic placeholder image as the cover if not found.

The basic idea would be to have it as it's own source, just like how you need to pick your current source as present.  However instead of it being based off of one of the existing sources it's based off of the local Filesystem.  Thus keeping the collection completely seperate to those of other sources.

**Comment by jparkie** [comment]
I understand having a new "Source", my problem is that to solve all the issue about this feature is too much of a hack and will be messy. Relying on the users too much to provide correct file formats is too much of a burden on them, so it is highly likely a surge of complaints would arise. Then for the users who are less technical but would like to try it out, they could complain it is too complex.

Overall, having this application act as two when it was designed for a certain purpose burdens the use case of the application such that this feature request should be a separate application.

**Comment by 16trohrt** [comment]
@jparkie What about adding support to read from a .cbz format?

**Comment by jparkie** [comment]
I feel the format is irrelevant. For .CBZ, it just needs to be temporarily unzipped to access the images. Then the same problems mentioned above applies. For .CBR, there is no modern and efficient RAR library for Java. The one that most people use in some applications have `OutOfMemory` problems while it is no longer maintained.
