### ISSUE TITLE
Option To Use ListView

### ISSUE THREAD

**Issue by dulleh** [jparkie/Aizoban#39]
What do you think of an option to use a ListView in the Catalogue (like the one used in Favourites) and an option in favourites to use a GridView?

**Comment by jparkie** [comment]
I started work on 2.0.+ yesterday. I'm a switch all ListViews and GridViews to RecyclerViews so you can switch the appearance.

**Comment by jparkie** [comment]
I'm trying to decide for the new `data` layer whether it should expose a repository like the current `QueryManager` to provide results as `Cursor`s or actual POJOs for the `RecyclerView.Adapter`s to consume. I wonder if there is any drastic performance concerns. Currently the new `QueryManager` can retrieve results as both `Cursor`s and `POJO`s while hiding now the Cupboard dependency from its use. Furthermore, adapters can rely on the new `DatabaseUtils` to map `Cursor`s to POJOs.
