### ISSUE TITLE
Downloading to External Storage

### ISSUE THREAD

**Issue by jparkie** [jparkie/Aizoban#4]
>
**Myst Redd on Dec 20, 2014 at 8:13 PM**
_Full Screen,bugs and NOTIFIER Can you add an option to view it full screen and the mangas are downloaded in internal storage even thoigh i check enable to save on external storage. Also can you add a notifier if there is a new chapter released_
>

>
**Chris yung on Dec 19, 2014 at 10:07 PM**
_Good reader Good job mate. Small issue with the mangas mot downloading to the sd card when the option is selected_
>

**Comment by jparkie** [comment]
The check did not fix this issue. I'm suspecting that it might be a bug in `Environment.getExternalStorageDirectory` on different versions of Android.

**Comment by jparkie** [comment]
See comit ce54ea34072e0427febd1285ab4cf36edc0fefab.

**Comment by jparkie** [comment]
The hacked fix did not fix it. Apparently some device manufactures have both an internal `sdcard0` and an external `extsdcard`. Such that `Environment.getExternalStorageDirectory()` can actually return internal storage.

**Comment by jparkie** [comment]
Possible Solution:
- http://stackoverflow.com/questions/11281010/how-can-i-get-external-sd-card-path-for-android-4-0
- http://stackoverflow.com/questions/15744064/cant-check-if-file-on-sdcard-exists/15744282#comment22381234_15744282

**Comment by tzinmein** [comment]
Hello Jacob,

This technique worked for me:

http://stackoverflow.com/questions/9340332/how-can-i-get-the-list-of-mounted-external-storage-of-android-device/19982338#19982338

**Comment by jparkie** [comment]
Thanks so much for the link! I'll try to use it.

**Comment by jparkie** [comment]
![1](https://cloud.githubusercontent.com/assets/9499097/5803795/f9cff668-9fce-11e4-811d-8ad9cc55b219.png)
![2](https://cloud.githubusercontent.com/assets/9499097/5803797/fbe29384-9fce-11e4-8510-84b99a9aead3.png)

**Comment by jparkie** [comment]
Sources:
http://stackoverflow.com/questions/13976982/removable-storage-external-sdcard-path-by-manufacturers
http://www.androidpolice.com/2014/02/17/external-blues-google-has-brought-big-changes-to-sd-cards-in-kitkat-and-even-samsung-may-be-implementing-them/
https://source.android.com/devices/storage/

The current solution does not work on KitKat onwards as they are read-only. New solution:
`Context.getExternalFilesDirs()`, `Context.getExternalCacheDirs()`, and `Context.getObbDirs()`.
