### ISSUE TITLE
more sources 

### ISSUE THREAD

**Issue by mitsuketta** [jparkie/Aizoban#40]
Can you add sources in Spanish, like es.ninemanga or submanga. Thanks for your work.

**Comment by KaitoKito** [comment]
Hi jparkie, thousands thanks for this amazing app (discovered via Fdroid).
I'd also like if you can add more source, especially in French, my native language, and also others languages not added yet.

I wish you a great day.
Kaito.

**Comment by jparkie** [comment]
I am currently working on Version 2.0.+, thus, implementing sources will be on hold. Eventually, since I have Batoto (EN), I'll try to implement the other languages of it at least.

**Comment by KaitoKito** [comment]
Great :) Can't wait to see the 2.0 version then.

**Comment by Tabaluga** [comment]
Yes we need indeed more sources. Best regards
