### ISSUE TITLE
New App Icon

### ISSUE THREAD

**Issue by GreyAsteroid** [jparkie/Aizoban#54]
I'm aware that Aizoban is currently abandoned but people ocassionally fork it so I figured I'd post his.

https://plus.google.com/102718493746376292361/posts/GvAqeJLp7zv

If anyone is looking to maintain Aizoban it would be a waste to just let the new icon be lost and I'm sure Michael Cook (cookicons) would be willing to provide the files.

**Comment by CheviOne** [comment]
It looks pretty awesome but the a itself is too weak compared to the original. As app icon alone it will definitely works fine, however there are two more cases: downloader/status bar and splash screen at start. I'm going to add this icon my fork, then everyone can make his own picture about.

**Comment by GreyAsteroid** [comment]
I mentioned getting into contact with the creator for that reason. Considering he posted the icon as a sample on his website I assume he still has the psd for it and could provide the files for a serious fork which would make replacing the splash screen "a" and downloader/status bar icon a matter of deleting a few layers and exporting.

**Comment by CheviOne** [comment]
I will do that in the next few days.
