### ISSUE TITLE
Notifications for New Updates for Favourite Manga

### ISSUE THREAD

**Issue by jparkie** [jparkie/Aizoban#8]
>
**Mesha Michael Savio on Jan 3, 2015 at 11:22 AM**
_Very nice. This is such a great app. One feature I'd like to have, that everyone mentioned, are the automatic checking for new chapters in our favorites list every few hours and second a push notification about it. And the other feature I'd love is to be able to save backups of our favorites at any time, and being able to restore them later on. Other than these, this is a very, very great app. Love the material design looks!_
>
>
**Muhammad Ruslan on Jan 1, 2015 at 7:02 PM**
_Well done Well done. But you deserve 5 stars if there is notification for new updates on favourite manga. Nice work_
>

References:
[Scheduling Repeating Alarms](https://developer.android.com/training/scheduling/alarms.html)
[Notifying the User](http://developer.android.com/training/notify-user/index.html)

**Comment by jparkie** [comment]
**Concern**: Without a server to provide chapter updates, each manga in the `FavouriteMangaFragment` fragment must be checked manually by calling their web pages. Accordingly, this might use a lot of data?

I think I will implement it, but I don't know how well it will work. I have a general idea how to determine new updates, but I am not sure how to notify the user properly to show updates if there are a lot. I wish to avoid any schema migrations for `Manga` or `FavouriteManga`.

**Comment by jparkie** [comment]
Approximately for each favourited manga, an average of 75 KB of bandwidth is required to download the HTML file. Unless, I introduce a limit to the number of manga which could be checked. It can approach concerning bandwidth drain (i.e. 100 = 7.5 MB, 1000 = 75 MB). 

Furthermore, the HTML needs to be checked for new chapters against the device. This can be achieved by either parsing chapters and comparing the chapter count to the device's. Furthermore, only the chapter links can be counted instead of updating, but no indication of which chapter could probably be saved. In addition, the payload size could be compared. Nonetheless, the increasing options increase in speed from average 1 second to few milliseconds but with increasing unreliability.

**Comment by beepFTW** [comment]
Thank you for the update!

**Comment by jparkie** [comment]
Currently, I do not plan on releasing this feature. Current implementations are substandard. I find this feature unfeasible without the use of a cloud service to push the notifications. Furthermore, the implementation or use of a cloud service is too much responsibility to maintain as a hobby project to have a web crawler fetch updates for all manga across all sources.

Thus, this issue will be closed and labeled "wontfix" for now.

**Comment by sebastiaopf** [comment]
Sorry for posting on this old thread. Would you consider adding the feature and letting the user choose if he/she wants the bandwidth consumption? And/or add an option to check for updates only when connected via wifi, not mobile network.

BTW thanks for the great work with this app.
